### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by naazguu** [googleapis/nodejs-promisify#123]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

How to use ?

Hello Brother

I'm following the procedures according to the video where I have not been successful so far, can you help me please

https://youtu.be/hLInX0WcGOU

**Comment by JustinBeckwith** [comment]
Greetings!  The quickstart here pretty much covers it:
https://github.com/googleapis/nodejs-promisify

That having been said - this is mostly an internal module we use for our own npm modules.  If you're looking for a generic promisification module, I highly recommend using pify:
https://github.com/sindresorhus/pify

Hope this helps!
