### ISSUE TITLE
promisify should infer proper types for the returned wrapped function

### ISSUE THREAD

**Issue by carnesen** [googleapis/nodejs-promisify#20]
Currently `promisify` returns a `wrapped` function typed as `any`. Instead it should use the types of the input function to infer the signatures of the return function. This isn't easy, but it sure is useful. In the `@google-cloud` libraries that `promisifyAll` their classes, the current approach of declaring the post-promisified method signatures "manually" alongside the pre-promisified implementation ([see here for example](https://github.com/googleapis/nodejs-common/blob/24b3efeb29dd38689169c823321c3a254624cd16/src/service-object.ts#L366)) is somewhat confusing and definitely error-prone (see https://github.com/googleapis/nodejs-common/pull/240  for example).

For inspiration, here is how Node.js's promisify is typed https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v8/index.d.ts#L5691

**Comment by sofisl** [comment]
Hi @carnesen, currently putting this library in maintenance mode.
